name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Install project dependencies
        run: poetry install

      - name: Install semantic-release
        run: poetry run pip install python-semantic-release

      - name: Run semantic-release version
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: poetry run semantic-release version

      - name: Run semantic-release publish
        env:
          PYPI_USERNAME: __token__
          PYPI_PASSWORD: ${{ secrets.TEST_PYPI_PASSWORD }}
        run: poetry run semantic-release publish
